version: '3.8'

networks:
  ormuz_net:
    driver: overlay # Mantendo a compatibilidade com o seu Swarm
    attachable: true # Permite que os containers se conectem dinamicamente

services:
  # ==========================================
  # CAMADA DE ESTADO (A BLOCKCHAIN)
  # ==========================================
  ledger_app:
    build:
      context: .
      dockerfile: deployments/docker/ledger.Dockerfile
    networks:
      - ormuz_net
    ports:
      - "26658:26658"

  comet_node:
    image: cometbft/cometbft:v1.0.0
    networks:
      - ormuz_net
    ports:
      - "26657:26657" # Porta RPC exposta para os Brokers
    depends_on:
      - ledger_app
    entrypoint: ["sh", "-c"]
    # O comando abaixo inicializa a génese da blockchain se não existir, e depois liga o nó à nossa App Go
    command: >
      "cometbft init --home /cometbft || true && 
      cometbft node --home /cometbft 
      --proxy_app=tcp://ledger_app:26658 
      --rpc.laddr=tcp://0.0.0.0:26657"

  # ==========================================
  # CAMADA DE ROTEAMENTO TÁTICO (BROKERS)
  # ==========================================
  broker:
    build:
      context: .
      dockerfile: deployments/docker/broker.Dockerfile
    networks:
      ormuz_net:
        aliases:
          - tasks.broker # O DNS vital para o Consistent Hashing
    environment:
      - TOTAL_SECTORS=25
      - COMET_URL=http://comet_node:26657 # Aponta para o motor de consenso
      - UDP_PORT=9000
      - HTTP_PORT=8080
    deploy:
      replicas: 3 # Instancia 3 brokers para testar a Sala de Espera e o Gossip
    depends_on:
      - comet_node

  # ==========================================
  # CAMADA DE BORDA (GERADOR DE CARGA)
  # ==========================================
  sensor:
    build:
      context: .
      dockerfile: deployments/docker/sensor.Dockerfile
    networks:
      - ormuz_net
    env_file:
      - .env # Carrega os parâmetros de stress test
    depends_on:
      - broker

  station:
    build:
      context: .
      dockerfile: deployments/docker/station.Dockerfile
    networks:
      ormuz_net:
        aliases:
          - tasks.station # DNS nativo para Round-Robin (Self-Healing)
    environment:
      - BROKER_URL=http://tasks.broker:8080
      - PORT=8081
    deploy:
      replicas: 2 # Iniciamos com 2 Estações
    depends_on:
      - broker

  # ==========================================
  # CAMADA DE EXECUÇÃO AUTÓNOMA (DRONES)
  # ==========================================
  drone:
    build:
      context: .
      dockerfile: deployments/docker/drone.Dockerfile
    networks:
      - ormuz_net
    environment:
      - STATION_URL=http://tasks.station:8081
      - COMET_URL=http://comet_node:26657
    deploy:
      replicas: 5 # Uma frota de 5 Drones a patrulhar
    depends_on:
      - station